blank_issues_enabled: false
contact_links:
  - name: Extension Store Documentation
    url: https://github.com/1311-hack1/Extension-Store/blob/master/.github/ISSUE_TEMPLATE/new-extension.md
    about: Please read our documentation before submitting an extension.
